spring.application.name=back-end

spring.datasource.url=jdbc:mysql://172.21.93.69:3306/cms
spring.datasource.username=root
spring.datasource.password=vTVi8Z92HHPKhTLxdShwrGoD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.web.resources.static-locations=classpath:/static/

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

api.path=/api/

jwt.secret=clinic-management-system-jwt-secret-key-2026-secure